### ISSUE TITLE
Domain Sync Issue

### ISSUE THREAD

**Issue by immdraselkhan** [namesilo/whmcs#1]
How can I set up domain sync corn? Should I set up it or automatically it will work?

**Comment by namesilo** [comment]
Hi,

This would be done directly through whmcs

**Comment by angel9215** [comment]
Support for price sync (7.10) was just added, support for other sync functions (domain sync and transfer sync) should be there already, not sure if it works

**Comment by angel9215** [comment]
We tested both domain sync and transfer sync a few days ago and didn't find any problem, you should be able to sync your domains if you set namesilo as your default registrar for a TLD and configure it on the automation settings

**Comment by anayat031** [comment]
Hello Namesilo Support Team,
We asking create a cronjob for whmcs namesilo that's run daily automatically and sync all domains TLD with our margin price, such as we want 30% margin or $2+1%  margin. Please help to your resellers for solve this issue.
all reseller want this work daily base and automatic.
