### ISSUE TITLE
Sync Redemption Fees

### ISSUE THREAD

**Issue by MrFreezia** [namesilo/whmcs#12]
The pricing sync doesn't seem to support syncing redemption fees.. nor does it support the ability for the grace or redemption statuses.

**Comment by jas8522** [comment]
For the grace or redemption status, see issue #3 -- I have a solution in a fork here: https://github.com/websavers/WHMCS-NameSilo/

Unfortunately as last check the redemption fees were not provided by the NameSilo API. See comments on lines 1644 and 1645 here: https://github.com/websavers/WHMCS-NameSilo/blob/master/namesilo.php
